# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

      body=
      
       {
            "contributionIds": [
                "ms.vss-admin-web.admin-teams-data-provider"
              ]
            "dataProviderContext": {
                          "properties": {
                              "setTeamAdmins": true,
                              "teamDescriptor": "vssgp.Uy0xLTktMTU1MTM3NDI0NS0zMzY2MDExNzEwLTEwMjMzNjUxODgtMzIxMDQ4NDIxMS00MTE2NDUwMTQxLTEtMTczNDk4MDgzLTM1MTI0OTk1MzAtMjc2NDQwNDExOC00NjEzMjk1NDk",
                              "admins": [
                                  "msa.YTIyOWViMGMtNTk4OC03Y2UzLWE0YWMtZjhkODZmNmM5Y2I0"
                                 ],
            "sourcePage": {
                "url": "https://dev.azure.com/azclouddev01/AZCLOUDDEV01/_settings/teams?subjectDescriptor=vssgp.Uy0xLTktMTU1MTM3NDI0NS0zMzY2MDExNzEwLTEwMjMzNjUxODgtMzIxMDQ4NDIxMS00MTE2NDUwMTQxLTEtMTczNDk4MDgzLTM1MTI0OTk1MzAtMjc2NDQwNDExOC00NjEzMjk1NDk",
                "routeId": "ms.vss-admin-web.project-admin-hub-route",
                "routeValues": {	
                     "project": "AZCLOUDDEV01",
                     "adminPivot": "teams",
                      "controller": "ContributedPage",
                      "action": "Execute",
                      "serviceHost": "41a5112a-aa0f-4eef-8ff7-9fc277bdbeb5 (azclouddev01)"
        }
      }
    }
  }
}

      # Send the POST request using curl
      response=$(curl -X POST -H "Content-Type: application/json" -d "$body" "$url")

      # Print the response
      echo "$response"
