# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'



- ${{ if eq(variables['environment'], 'dev') }}:
  - task: AzureCLI@2
    displayName: 'Run Prod Task'
    inputs:
      azureSubscription: 'Azure subscription 1'
      scriptLocation: 'inlineScript'
      inlineScript: 'az --version'
